// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Novira.Backend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Novira.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816074434_AddVerifiedProfileFields")]
    partial class AddVerifiedProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Novira.Backend.Models.MagicLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MagicLinkTokens");
                });

            modelBuilder.Entity("Novira.Backend.Models.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("MinEducationLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("MonthlyCompensationEur")
                        .HasColumnType("integer");

                    b.Property<string>("OccupationField")
                        .HasColumnType("text");

                    b.Property<int>("Path")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequiredEnglishLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("RequiredGermanLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresCertifiedLanguageProof")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TuitionFeeEur")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("Novira.Backend.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Novira.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DesiredPath")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EnglishLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("FinancialSituation")
                        .HasColumnType("integer");

                    b.Property<string>("FraudFlagNote")
                        .HasColumnType("text");

                    b.Property<bool>("FraudFlagged")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FraudFlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int?>("GermanLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("GermanyConnection")
                        .HasColumnType("integer[]");

                    b.Property<int?>("HighestEducation")
                        .HasColumnType("integer");

                    b.Property<int?>("LanguageCertificate")
                        .HasColumnType("integer");

                    b.Property<string>("OccupationField")
                        .HasColumnType("text");

                    b.Property<int?>("PassportStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProfileUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegionFlexibility")
                        .HasColumnType("integer");

                    b.Property<int?>("StartTimeline")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerifiedDataUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifiedDateOfBirth")
                        .HasColumnType("text");

                    b.Property<int?>("VerifiedEnglishLevel")
                        .HasColumnType("integer");

                    b.Property<string>("VerifiedFieldOfStudy")
                        .HasColumnType("text");

                    b.Property<string>("VerifiedFullName")
                        .HasColumnType("text");

                    b.Property<int?>("VerifiedGermanLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("VerifiedHighestEducation")
                        .HasColumnType("integer");

                    b.Property<string>("VerifiedNationality")
                        .HasColumnType("text");

                    b.Property<string>("VerifiedPassportExpiryDate")
                        .HasColumnType("text");

                    b.Property<string>("VerifiedPassportNumber")
                        .HasColumnType("text");

                    b.Property<int?>("VerifiedPassportStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Novira.Backend.Models.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiExtractedDataJson")
                        .HasColumnType("text");

                    b.Property<string>("AiExtractedName")
                        .HasColumnType("text");

                    b.Property<string>("AiFlagsJson")
                        .HasColumnType("text");

                    b.Property<bool?>("AiNameMatchesProfile")
                        .HasColumnType("boolean");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<int>("AiVerificationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AiVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RejectionMessageSent")
                        .HasColumnType("boolean");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageBlobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("Novira.Backend.Models.MagicLinkToken", b =>
                {
                    b.HasOne("Novira.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Novira.Backend.Models.Session", b =>
                {
                    b.HasOne("Novira.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Novira.Backend.Models.UserDocument", b =>
                {
                    b.HasOne("Novira.Backend.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
